name: sample-rust-tide-deps
services:
- name: tide-api
  dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: bojand/sample-rust-tide
  envs:
    - key: PUBLIC_URL
      scope: RUN_TIME
      value: ${_self.PUBLIC_URL}